apiVersion: v1
kind: Secret
metadata:
  name: business-api-secrets
  namespace: estatekit
  labels:
    app: estatekit
    component: business-api
    environment: production
    security-tier: critical
    rotation-schedule: 90-days
  annotations:
    rotation-timestamp: "2024-01-01T00:00:00Z"
    last-accessed: "2024-01-01T00:00:00Z"
    encryption-key-version: "v1"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "business-api"
    vault.hashicorp.com/agent-inject-status: "update"
    security.estatekit.com/audit-enabled: "true"
    security.estatekit.com/backup-enabled: "true"
    security.estatekit.com/multi-region: "true"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "${BASE64_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${BASE64_AWS_SECRET_ACCESS_KEY}"
  AWS_KMS_KEY_ID: "${BASE64_AWS_KMS_KEY_ID}"
  JWT_SIGNING_KEY: "${BASE64_JWT_SIGNING_KEY}"
  DATA_API_AUTH_TOKEN: "${BASE64_DATA_API_AUTH_TOKEN}"
  TEXTRACT_API_KEY: "${BASE64_TEXTRACT_API_KEY}"
  ENCRYPTION_VERSION: "${BASE64_ENCRYPTION_VERSION}"
  KEY_ROTATION_TIMESTAMP: "${BASE64_KEY_ROTATION_TIMESTAMP}"
  EMERGENCY_ACCESS_KEY: "${BASE64_EMERGENCY_ACCESS_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: data-api-secrets
  namespace: estatekit
  labels:
    app: estatekit
    component: data-api
    environment: production
    security-tier: critical
    rotation-schedule: 90-days
  annotations:
    rotation-timestamp: "2024-01-01T00:00:00Z"
    last-accessed: "2024-01-01T00:00:00Z"
    encryption-key-version: "v1"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "data-api"
    vault.hashicorp.com/agent-inject-status: "update"
    security.estatekit.com/audit-enabled: "true"
    security.estatekit.com/backup-enabled: "true"
    security.estatekit.com/multi-region: "true"
type: Opaque
data:
  POSTGRES_CONNECTION_STRING: "${BASE64_POSTGRES_CONNECTION_STRING}"
  ENCRYPTION_MASTER_KEY: "${BASE64_ENCRYPTION_MASTER_KEY}"
  AWS_KMS_KEY_ID: "${BASE64_AWS_KMS_KEY_ID}"
  AWS_ACCESS_KEY_ID: "${BASE64_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${BASE64_AWS_SECRET_ACCESS_KEY}"
  API_AUTH_TOKEN: "${BASE64_API_AUTH_TOKEN}"
  ENCRYPTION_VERSION: "${BASE64_ENCRYPTION_VERSION}"
  KEY_ROTATION_TIMESTAMP: "${BASE64_KEY_ROTATION_TIMESTAMP}"
  EMERGENCY_ACCESS_KEY: "${BASE64_EMERGENCY_ACCESS_KEY}"